### ISSUE TITLE
Be able to follow and be warned when using balls for too long (hours of play as well as opening of the balls)

### ISSUE THREAD

**Issue by Edenglish92** [gitjpk/stringz#4]
It would be great to be able to measure the usage of the tennis balls to identify when they are too old or too used.
It would also help us to compare longevity of different brands or types of balls.
It would be nice to be able to setup balls on the Settings tab and then to select it when adding a play line on Data.

**Comment by gitjpk** [comment]
addressed in 2.2 using new setting : "Hours played to change balls" and new row "Count for ball usage" in datas. This new row need to be adjusted when copy pasting from previous version of the file.
